name: rest_countries_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  http: ^0.13.4
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Nunito_Sans
      fonts:
        - asset: assets/fonts/Nunito_Sans/NunitoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito_Sans/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito_Sans/NunitoSans-ExtraBold.ttf
          weight: 800
